### ISSUE TITLE
Configure Error! java@0.5.1 install: 'node.gyp rebuild'

### ISSUE THREAD

**Issue by ramyadirsumilli** [joeferner/node-java#210]
I am trying to install java to nodejs using 'npm install java'

I have already run node-gyp rebuild and gave me a result 'ok'!
![screenshot 5](https://cloud.githubusercontent.com/assets/4921610/7232753/9fe83344-e77d-11e4-9f27-b5538c846d54.png)

But I still get an error while installing java to nodejs.

![screenshot 4](https://cloud.githubusercontent.com/assets/4921610/7232731/8bd5e914-e77d-11e4-9a3a-64acea312141.png)
npm -v 1.4.28 npm ERR! code ELIFECYCLE npm ERR! not ok code 0

I use Windows 8.1, Java 1.8.0_35, nodejs - 0.10.36, npm- 1.4.28

**Comment by lucastanziano** [comment]
![image](https://cloud.githubusercontent.com/assets/9505308/7539008/555346d6-f5a4-11e4-98bf-df4cc21d616a.png)

Same error here. Win 7 x64, Java 1.7.2

Any news? Ideas?

**Comment by jsdevel** [comment]
can you upload your npm-debug.log file?

**Comment by lucastanziano** [comment]
after further tests I figured out the issue. It was about the Python path.
This command executed before npm install java solved the problem.
"npm config set python c:/Python27/python.exe"

I had PYTHON=C:/Python27   in my environment variables but evidently it wasn't enough. 

Then in the verbose log this line was misleading: 

"gyp verb check python checking for Python executable "c:/Python27" in the PATH
gyp verb `which` succeeded c:/Python27 c:/Python27"

In my understanding it should state that it succeeded to validate the Python path, but then it fails because somewhere it needs the more specific python.exe path instead.. 

It would be nice to specify this in the documentation as well as to perform some checks during the installation. A message like "Error: you have an invalid Python path. A proper one should look like C:/Pythonxx/python.exe"  would have saved to me some hours.

**Comment by ramyadirsumilli** [comment]
Thank you @lucastanziano .. That python path setting worked. But now I have a new trouble.
![screenshot 8](https://cloud.githubusercontent.com/assets/4921610/7569044/80cd5860-f806-11e4-8d06-39760581061e.png)

**Comment by lucastanziano** [comment]
check to have everything built for the same architecture. That kind of error usually occurs when you have Node.JS 32bit and Java JDK 64bit or viceversa.
I see that you have Node and Visual Studio 32bit. Which Java are you using?

**Comment by ramyadirsumilli** [comment]
I have reinstalled everything to be 32bit. 
But I still have the same issue.

**Comment by lucastanziano** [comment]
libcmpt.lib is a file from Win32 SDK  (https://support.microsoft.com/en-us/kb/94248/)
If it cannot open it for linking purposes the cases are two:
- Visual Studio installation is broken/has some missing files -> try reinstalling it (http://go.microsoft.com/?linkid=9816758)
- the file it is trying to link to it has a different architecture from 32bit. Maybe an old 64bit Java installation path among environment variables?

I cannot guess anything else.

**Comment by ramyadirsumilli** [comment]
Rebuild individually is working, 
But while installing java I am getting the error!
![screenshot 9](https://cloud.githubusercontent.com/assets/4921610/7570869/c1984bd6-f813-11e4-8844-44ecd3bc9026.png)

**Comment by jimlloyd** [comment]
Is your python 64-bit? If so try installing 32-bit python.

**Comment by ramyadirsumilli** [comment]
@jimlloyd  i have python 2.7 32bit

**Comment by ramyadirsumilli** [comment]
I tried 'npm install java --msvs_version=2012'
And it worked. 
Now I have java installed in my node.js

**Comment by jsdevel** [comment]
w0ot!
