### ISSUE TITLE
Can't access inherited methods

### ISSUE THREAD

**Issue by dannyn-mirth** [joeferner/node-java#222]
I'm trying to incorporate JasperReports into my Node project and I'm having problems with calling a method that is inherited.

I imported a class called 'net.sf.jasperreports.engine.export.ooxml.JRXlsxExporter'

Now, JRXlsxExporter extends JRXlsAbstractExporter

JRXlsAbstractExporter has a method called setExporterInput

I have in my code:

1  var JRXlsxExporter = java.import('net.sf.jasperreports.engine.export.ooxml.JRXlsxExporter');
2 JRXlsxExporter.setExporterInput(...);

At line two, I'm getting a "undefined is not a function" error. Am I doing something wrong or is it this a limitation of node-java?

**Comment by jimlloyd** [comment]
You should be able to get this to work, i.e. there isn't any limitation of node-java that should prevent this.

I believe the main problem with your code is that you are assuming that JRXlsxExporter is an instance of the class, but it is actually a proxy object that you can use in a constructor expression. Try this:

```
var JRXlsxExporter = java.import('net.sf.jasperreports.engine.export.ooxml.JRXlsxExporter');
var aJRXlsxExporter = new JRXlsxExporter(); // pass in ctor parameters if necessary
aJRXlsxExporter.setExporterInputSync(...);
```

Note that the above uses `setExporterInputSync()` instead of `setExporterInput()`. If you use the latter, then be aware you need to add a callback function as the final argument.

**Comment by dannyn-mirth** [comment]
Wow thank you, that worked! If this was StackOverflow you'd get a check mark and an upvote, haha.
