### ISSUE TITLE
Switch Java heap memory profile at runtime

### ISSUE THREAD

**Issue by loretoparisi** [joeferner/node-java#384]
I have a java jar library that requires an important amount of memory during some kind of operations  i.e. long tasks (that may require to load huge data into memory, etc.) I'm then setting the heap as usual:

```
java.options.push('-Xmx4096m');
```

This settings is not needed during during the ordinary usage of the modules i.e. short tasks, api calls, etc. My guess is if I could then start with a memory profile with lower memory requirements for running tasks like lambda tasks:

```
java.options.push('-Xmx2048m');
var myModuleInstance = java.newInstanceSync("com.mycompany.mymodule");
myModuleInstance.lambdaTask(params);
```

then switch to a different memory profile that may require more memory i.e. long tasks, etc.

```
java.options.push('-Xmx4096m');
var myModuleInstance = java.newInstanceSync("com.mycompany.mymodule");
myModuleInstance.longBackgroundTask(params);
```

**Comment by jzakrzewski** [comment]
Due to the way the JVM works it's not possible. You are setting the startup options. They can only be applied during VM initialization. Once this happens it's over. Only on JVM instance is allowed per process and shutting down in-process JVM has been broken for ages.

I can see no harm in setting higher value upfront. It only sets the upper limit and does not allocate the memory if it's not needed.
