### ISSUE TITLE
JDK9 Bad Path for `libjvm.dylib`

### ISSUE THREAD

**Issue by peisenmann** [joeferner/node-java#411]
Attempting to install a fresh copy of node-java with JDK9 installed yields the following error:

```
ld: warning: directory not found for option '-L/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/jre/lib/server'
ld: library not found for -ljvm
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/nodejavabridge_bindings.node] Error 1
```

I believe this is because there is no `.../Home/jre/lib` only a `...Home/lib`

```
14:49 $ ls /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/server/
Xusage.txt	libjsig.dylib	libjvm.dylib
```

I believe this post details changes in the structure for the JDK in version 9: http://openjdk.java.net/jeps/220

**Comment by peisenmann** [comment]
As a workaround, I was able to simply symlink a fake jre directory back to the Home directory.

```
cd /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
sudo ln -s ./ jre
```

**Comment by groodt** [comment]
I've run into the same issue. Any thoughts on how node-java could be extended to support JDK9?

**Comment by peisenmann** [comment]
@groodt I think it could just a matter of checking what paths exist. I was able to work around it quick enough with a symlink. Not sure how insidious this would be to PR, but I might try at some point if this keeps popping up as a problem for my team.

**Comment by r4zzz4k** [comment]
In my current project I'm setting GYP_DEFINES env variable before bulding the project like this:
```
export GYP_DEFINES="javalibdir=\"$JAVA_HOME/lib/server\""
```
As for the proper solution, I think `binding.gyp` should delegate searching for `javalibdir` to some JS script in similar way as `lib/nodeJavaBridge.js` is used, because it should be easier to match `os.platform()` to JDK naming than to put a lot of similar things in gyp config. I was going to update that at some point if nobody else catches up with that earlier but don't have enough time to contribute generic solution right now.
As I see it, somebody should find out naming part and check if OpenJDK and Oracle JDK are using identical paths to `libjvm.so` or not for that matter.

**Comment by r4zzz4k** [comment]
Also, I think it's a reasonable thing to allow for easier `JAVA_HOME` overriding from outside for cases when `javapackager` / `jlink` is used and JDK is located in app distro. It can eliminate need to install full-blown JDK on target system, when Node.js / Electron app uses Java code.

**Comment by andrewleo** [comment]
So now how can I change the JAVA_HOME? node-java now use Java on target system.

**Comment by r4zzz4k** [comment]
Sorry for not seeing your message earlier. You can put absolute path into the `export` command I mentioned above instead of relying on `JAVA_HOME`, or do something like
```sh
export JAVA_HOME=/your/own/path/to/jdk
export GYP_DEFINES="javalibdir=\"$JAVA_HOME/lib/server\""
```
So both `node-java` and all the other stuff which relies on aforementioned variable know where to find it.

**Comment by electricmonk** [comment]
still happens
