### ISSUE TITLE
OS X JDK 1.7 failing to load

### ISSUE THREAD

**Issue by jahewson** [joeferner/node-java#90]
I'm using OS X 10.9 with Sun's JDK 1.7 and always get the following error:

```
JavaVM: Failed to load JVM: /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/bundle/Libraries/libserver.dylib
JavaVM FATAL: Failed to load the jvm library.
JavaVM: Failed to load JVM: /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/bundle/Libraries/libserver.dylib
JavaVM FATAL: Failed to load the jvm library.
Segmentation fault: 11
```

Indeed, the folder `/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/bundle` does not exist on my system.

I'm using Sun's JDK 1.7, and do not have Apple's installed. The output of `java -version` is:

```
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)
```

**Comment by seshness** [comment]
Thanks, @TheSpyder! That was super helpful.
It looks like the homebrew cask installation for Java 7 now applies your first suggested workaround: https://github.com/caskroom/homebrew-versions/blob/master/Casks/java7.rb#L17

Installation steps for the next person to stumble upon this issue:
```sh
$ brew install caskroom/cask/brew-cask
$ brew tap caskroom/homebrew-versions
$ brew cask install java7
```

**Comment by junqdu** [comment]
@TheSpyder any idea why JDK doesn't advertise itself as supporting JNI?

**Comment by TheSpyder** [comment]
@junqdu no idea. I don't think Oracle cares about Java on OS X much anymore.

**Comment by scottellis64** [comment]
Adding JNI to the list of JVMCapabilities worked perfectly for me.

**Comment by caiyufei** [comment]
@TheSpyder Thanks for your solution,  adding JNI also works for me! Thanks !!

**Comment by ctrueden** [comment]
@TheSpyder @jsdevel There is another, better way to avoid this horrible issue: load `libjli` before loading `libjvm`. The ImageJ project [uses this trick for its launcher](https://github.com/imagej/imagej-launcher/commit/efaea16049ded0adba625238bf9c769798c4a18a) successfully. And [here is another example of a project using this solution](https://github.com/xamarin/java.interop/pull/198). A big advantage of this approach is that users do not need to manually tweak their Java installations in order to get up and running.

**Comment by jsdevel** [comment]
nice @ctrueden !  can you open a pr?

**Comment by TheSpyder** [comment]
Interesting. That ImageJ dev seems to like to rant about Apple. I'm amused that there were three working methods to fix the same issue; perhaps the config patch only worked by accident.

Your second link (xamarin) points to this OpenJDK bug, which was fixed in Java 9:
https://bugs.openjdk.java.net/browse/JDK-7131356

So while this change is probably harmless on new releases, it seems only necessary on now-unsupported versions of Java (Java 8 fell out of Oracle support in Jan 2019).

> A big advantage of this approach is that users do not need to manually tweak their Java installations in order to get up and running.

Note that manual patching wasn't required for homebrew users, the cask did that in a post install script. Although [that was been removed](https://github.com/Homebrew/homebrew-cask/pull/52605/files#diff-6149815b24e8a7b72a9bd0e438920500L22) after someone discovered it didn't makes sense in Java 11.
